### ISSUE TITLE
Repository can't be cloned due to invalid path

### ISSUE THREAD

**Issue by K-Meech** [inform-us/requirements_specifications#11]
Attempting to clone the repo locally, currently errors with `error: invalid path 'informus/content/iand?_buttons_SPC.md'
fatal: unable to checkout working tree`

I assume this is an issue with including `?` in the filename?

**Comment by K-Meech** [comment]
@jhughes982 - do you get this same error?

**Comment by jhughes982** [comment]
Hmm, strangely I can clone the repo. I'm on Mac if that helps?

I have renamed the folders now to remove `?` from the path. So you can try cloning again.

**Comment by K-Meech** [comment]
Cloning works now - thanks! I guess it was a Windows specific issue.
